<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdverticeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdverticeRepository extends EntityRepository
{
    public function getFirst(){
        $qb = $this->createQueryBuilder('a');
        $qb->setMaxResults(1);
        $q = $qb->getQuery();
        
        return $q->getOneOrNullResult();
    }
}
