madybyrogal_admin:
    resource: "@MadybyrogalAdminBundle/Resources/config/routing.yml"
    prefix:   /admin/
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
